### ISSUE TITLE
MySQL 8.4 support

### ISSUE THREAD

**Issue by bmtcril** [Altinity/clickhouse-sink-connector#994]
Hi all,

From other issues here (#930) and my own testing it looks like the new replication syntax in MySQL 8.4 isn't supported. Are there any plans for this going forward? It's a blocker for us, unfortunately.

**Comment by subkanthi** [comment]
Hi @bmtcril , can you please explain the syntax thats not supported? Are u trying the lightweight or the kafka version?

**Comment by aadant** [comment]
@subkanthi I think @bmtcril refers to https://issues.redhat.com/browse/DBZ-7838 which is fixed in Debezium 3.0.

So I guess we need a build that uses Debezium 3.0.

**Comment by bmtcril** [comment]
Thanks all, @aadant is correct that's what I was looking for.

**Comment by subkanthi** [comment]
@aadant , @bmtcril , that debezium bug was fixed in `3.0.0.CR1`, the latest sink connector lightweight release uses `3.0.0.Final`, so it should have the fix.
https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector-lightweight/pom.xml

**Comment by bmtcril** [comment]
@subkanthi do you know which version of the lightweight image would have this? I'm using `registry.gitlab.com/altinity-public/container-images/clickhouse_debezium_embedded:latest` and still getting this error.

**Comment by subkanthi** [comment]
Please use this tag `altinity/clickhouse-sink-connector:2.5.0-lt` from the releases page https://github.com/Altinity/clickhouse-sink-connector/releases
``` 
Lightweight
Docker: altinity/clickhouse-sink-connector:2.5.0-lt
https://hub.docker.com/layers/altinity/clickhouse-sink-connector/2.5.0-lt/images/sha256-60d5edd7d89eeee4ec64ec802c95c223096793654cce256d58c4e15219c4d0e2?context=explore
```

**Comment by bmtcril** [comment]
Got it, thanks! That's solved that problem. Sorry for the fire drill.
